import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from "next/image";
import deved from "../public/dev-table.webp";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react';   // used for dark mode state

export default function Home() {
  // define variables for dark mode control
  const [darkMode, setDarkMode] = useState(false);
  return (
    // add a dark class to this div if it is selected
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Front End Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_vercel.svg" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>

        {/* Hero home screen section */}
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='font-epilogue text-xl'>John&apos;s Place</h1>
            <ul className='flex items-center'>
              {/* Use the button as a toggle for the dark mode (reverse the current state) */}
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className='cursor-pointer text-xl' /></li>
              <li>
                {/* Using a gradient to paint a button */}
                <a href="#" className='bg-gradient-to-r from-purple-400 to-purple-600 text-white rounded-md ml-8 px-4 py-1.5'>Resume</a>
              </li>
            </ul>
          </nav>

          {/* Have a round gradient bg for the image. used objectFit as a style prop in next.js 13   overflow-hidden */}
          <div className='relative mx-auto bg-gradient-to-b from-purple-500 rounded-full w-80 h-80 mt-20 md:w-96 md:h-96'>
            {/* Using path as an imported variable in a next.js specific image */}
            <Image src={deved} alt='Hero Image' fill style={{ objectFit: "contain" }} quality={70} />
          </div>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-purple-600 font-medium md:text-6xl dark:text-purple-400'>John Doe</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Front End Developer</h3>
            {/* Limit the paragraph width */}
            <p className='relative text-md py-5 leading-8 text-gray-800 md:text-lg max-w-xl mx-auto dark:text-gray-200'>
              Freelancer providing services for programming and design content needs. Join me down below and let&apos;s get cracking!
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-5 py-3 text-gray-600 dark:text-gray-400'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>

        </section>

        <section>
          <div>
            <h3 className='text-3xl py-2 dark:text-white'>Services I Offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              <span className='text-purple-500'> dolore </span> magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
              ex ea commodo consequat. Duis aute irure dolor in <span className='text-purple-500'> reprehenderit </span> in voluptate velit esse cillum dolore...
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              I offer from a wide range of services, including brand design, programming and teaching.
            </p>
          </div>

          {/* Services Cards */}
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={design} width={100} height={100} className='mx-auto' alt='Design' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core design theory.
              </p>
              <h4 className='py-4 text-purple-600'>Design Tools I Use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Indesign</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={code} width={100} height={100} className='mx-auto' alt='Code'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Code your dream project</h3>
              <p className='py-2'>
                Do you have an idea for your next great website? Let&apos;s make it a reality.
              </p>
              <h4 className='py-4 text-purple-600'>Design Tools I Use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Indesign</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={consulting} width={100} height={100} className='mx-auto' alt='Consulting'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Consulting</h3>
              <p className='py-2'>
                Are you interested in feedback for your current project? I can give you tips and tricks to level it up.
              </p>
              <h4 className='py-4 text-purple-600'>Design Tools I Use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Indesign</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white '>Portofolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum <span className='text-purple-500'> dolore </span> eu fugiat nulla pariatur.
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum...
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore...
            </p>
          </div>

          {/* Portfolio images section: large screens will have two images per wrapped row */}
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image responsive className='rounded-xl object-cover'  width={'100%'} height={'100%'} src={web1} alt='Project Preview'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image responsive className='rounded-xl object-cover' width={'100%'} height={'100%'} src={web2} alt='Project Preview'/>
            </div>
            <div className='basis-1/2 flex-1'>
              <Image responsive className='rounded-xl object-cover' style={{ objectFit: "cover" }} width={"100%"} height={"100%"} src={web3} alt='Project Preview'/>
            </div>
            <div className='basis-1/2 flex-1'>
              <Image responsive className='rounded-xl object-cover' width={'100%'} height={'100%'} src={web4} alt='Project Preview'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image responsive className='rounded-xl object-cover' width={'100%'} height={'100%'} src={web5} alt='Project Preview'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image responsive className='rounded-xl object-cover' width={'100%'} height={'100%'} src={web6} alt='Project Preview'/>
            </div>

          </div>
        </section>

      </main>
    </div>
  );
}
